apiVersion: v2
name: redisinsight
version: 0.1.0
description: RedisInsight - The GUI for Redis
type: application
keywords:
  - redis
  - gui
home: https://redis.com/redis-enterprise/redis-insight/
appVersion: "v1.0.0"
