---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redisinsight-chart.fullname" . }}
  labels:
    {{- include "redisinsight-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "redisinsight-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redisinsight-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redisinsight-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: db
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.redisinsight.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck/
              port: {{ .Values.redisinsight.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: {{ .Values.redisinsight.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          # Env Vars:
          #   ref: https://docs.redis.com/latest/ri/installing/configurations/
          env:
            - name: RIHOST
              value: {{ .Values.redisinsight.host | quote }}
            - name: RIPORT
              value: {{ .Values.redisinsight.port | quote }}
            - name: RIHOMEDIR
              value: {{ .Values.redisinsight.home_dir | quote }}
            - name: RILOGDIR
              value: {{ .Values.redisinsight.log_dir | quote }}
            - name: RITRUSTEDORIGINS
              value: {{ join "," .Values.redisinsight.trusted_origins | quote }}
          {{- if .Values.redisinsight.redis_servers }}
          lifecycle:
            postStart:
              exec:
                command:
                - "sh"
                - "-c"
                - |
                  {{- range .Values.redisinsight.redis_servers }}
                  curl -s -v -X "POST" "http://localhost:${RIPORT}/api/instance/"
                  -H "Content-Type: application/json; charset=utf-8"
                  -d '{
                    "host": "{{ .host }}",
                    "port": {{ .port }},
                    "password": "{{ .password }}",
                    "name": "{{ .name }}",
                    "connectionType": "{{ .connectionType }}",
                    "tls": {
                      "useTls": {{ .tls.useTls }},
                      "clientAuth": {{ .tls.clientAuth }},
                      "verifyServerCert": {{ .tls.verifyServerCert }}
                    }
                  }'
                  {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: db
              mountPath: {{ .Values.redisinsight.home_dir }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
