{{- $chart_name := include "cronjobs.fullname" . }}
{{- $chart_labels := include "cronjobs.labels" . }}

{{- if .Values.configMaps }}
{{- range $name, $map := .Values.configMaps }}
{{- $checksum := toYaml $map | sha256sum | trunc 20 | quote }}
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ $chart_name }}-{{ $name }}
  labels:
    {{- $chart_labels | nindent 4 }}
  annotations:
    values/checksum: {{ $checksum }}
data:
  {{- range $name, $value := $map.data }}
  {{ $name }}: |
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $name, $path := $map.files }}
  {{ $name }}: |
    {{- $.Files.Get $path | nindent 4}}
  {{- end }}
{{- end }}
{{- end }}

{{- range $job_name, $job := .Values.jobs }}
{{- if and (hasKey $job "extraFiles") $job.extraFiles }}
{{- $checksum := toYaml $job.extraFiles | sha256sum | trunc 20 | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "com.klicktipp.slugify-volume-name" (list $chart_name "files" $job_name) }}
  labels:
    {{- $chart_labels | nindent 4 }}
  annotations:
    values/checksum: {{ $checksum }}
data:
{{- range $filename, $file := $job.extraFiles }}
  {{- if $file.enabled }}
  {{ $filename }}: |
{{ $file.content | indent 4 }}
  {{- end }}
{{- end }} {{/* # end range extraFiles */}}
{{- end }} {{/* # end exists extraFiles */}}
{{- end }} {{/* # end range jobs */}}
