{{- if .Values.configMaps }}
{{- range $name, $map := .Values.configMaps }}
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "cronjobs.fullname" $ }}-{{ $name }}
  labels:
    {{- include "cronjobs.labels" $ | nindent 4 }}
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $name, $value := $map.data }}
  {{ $name }}: |
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $name, $path := $map.files }}
  {{ $name }}: |
    {{- $.Files.Get $path | nindent 4}}
  {{- end }}
{{- end }}
{{- end }}

{{- range $job_name, $job := .Values.jobs }}
{{- if and $job (hasKey $job "extraFiles") $job.extraFiles }}
{{- $checksum := toYaml $job.extraFiles | sha256sum | trunc 20 | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "com.klicktipp.slugify-volume-name" (list (include "cronjobs.fullname" $) "files" $job_name) }}
  labels:
    {{- include "cronjobs.labels" $ | nindent 4 }}
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- range $filename, $file := $job.extraFiles }}
  {{- if $file.enabled }}
  {{ $filename }}: |
{{ $file.content | indent 4 }}
  {{- end }}
{{- end }} {{/* # end range extraFiles */}}
{{- end }} {{/* # end exists extraFiles */}}
{{- end }} {{/* # end range jobs */}}
