{{- if .Values.rbac.create -}}
{{- if .Values.rbac.role.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cronjobs.fullname" . }}-role
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.rbac.role.annotations }}
    {{- toYaml .Values.rbac.role.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.annotations }}
    {{- toYaml .Values.rbac.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
rules:
  {{- if .Values.rbac.role.rules }}
  {{- toYaml .Values.rbac.role.rules | nindent 2 }}
  {{- end }}
{{- end }} {{/* # end rbac.role.createe */}}

{{- if .Values.rbac.clusterRole.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cronjobs.fullname" . }}-cluster-role
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.rbac.clusterRole.annotations }}
    {{- toYaml .Values.rbac.clusterRole.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.annotations }}
    {{- toYaml .Values.rbac.annotations | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
rules:
  {{- if .Values.rbac.clusterRole.rules }}
  {{- toYaml .Values.rbac.clusterRole.rules | nindent 2 }}
  {{- end }}
{{- end }} {{/* # end rbac.clusterRole.createe */}}
{{- end }} {{/* # end rbac.create */}}
