{{- $chart_labels := include "cronjobs.labels" . }}

{{- if .Values.dockerConfigJson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronjobs.fullname" . }}-registry
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
    {{- with $.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson | quote }}
{{- end }}

{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronjobs.fullname" . }}-{{ $name }}
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
    {{- with $.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- range $name, $value := $secret.data }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- range $name, $path := $secret.files }}
  {{ $name }}: {{ $.Files.Get $path | b64enc | quote }}
  {{- end }}
{{- end }}
