---
{{- range $job_name, $job := .Values.jobs }}
{{- $JOB_NAME_SLUG := include "com.klicktipp.slugify-volume-name" $job_name }}
{{- if and $job (hasKey $job "storage") (hasKey $job.storage "efs") (hasKey $job.storage.efs "mounts") }}
{{- range $efs_mount := $job.storage.efs.mounts }}
{{- range $efs_ap := $efs_mount.access_points }}
{{- $EFS_AP_ID_TRIMMED := trimPrefix "fsap-" $efs_ap.id }}
{{- $PV_NAME := include "com.klicktipp.slugify-volume-name" (list $.Release.Namespace $.Release.Name $JOB_NAME_SLUG $EFS_AP_ID_TRIMMED) }}
{{- $PVC_NAME := include "com.klicktipp.slugify-volume-name" (list $.Release.Name $JOB_NAME_SLUG (coalesce $efs_ap.name $efs_ap.path) $EFS_AP_ID_TRIMMED) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $PV_NAME }}
  annotations:
    storage.ktsys.cloud/efs_fs_id: {{ $efs_mount.fs_id | quote }}
    storage.ktsys.cloud/efs_name: {{ $efs_mount.fs_name | quote }}
    storage.ktsys.cloud/efs_ap_id: {{ $efs_ap.id | quote }}
    storage.ktsys.cloud/efs_path: {{ $efs_ap.path | quote }}
    {{- with $.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $efs_mount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  capacity:
    storage: 5Gi  # Any number will do, we are just required to specify a storage capacity
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ $job.storage.efs.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ $efs_mount.fs_id }}::{{ $efs_ap.id }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $PVC_NAME }}
  annotations:
    storage.ktsys.cloud/efs_fs_id: {{ $efs_mount.fs_id | quote }}
    storage.ktsys.cloud/efs_name: {{ $efs_mount.fs_name | quote }}
    storage.ktsys.cloud/efs_ap_id: {{ $efs_ap.id | quote }}
    storage.ktsys.cloud/efs_path: {{ $efs_ap.path | quote }}
    {{- with $.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $efs_mount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $job.storage.efs.storageClass }}
  volumeName: {{ $PV_NAME }}
  resources:
    requests:
      storage: 5Gi  # Any number will do, we are just required to specify a storage capacity

{{- end }} {{/* # end range $efs_ap */}}
{{- end }} {{/* # end range $efs_mount */}}
{{- end }} {{/* # end if storage.efs */}}
{{- end }} {{/* # end range volumes */}}
