---
{{- range $job_name, $job := .Values.jobs }}
{{- range $efs_mount := $job.storage.efs.mounts }}
{{- range $efs_ap := $efs_mount.access_points }}
{{- $PV_NAME := include "com.klicktipp.slugify-volume-name" (list $.Release.Namespace $.Release.Name $efs_ap.id) }}
{{- $PVC_NAME := include "com.klicktipp.slugify-volume-name" (list $.Release.Name (coalesce $efs_ap.name $efs_ap.path) $efs_ap.id) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $PV_NAME }}
  annotations:
    storage.ktsys.cloud/efs_fs_id: {{ $efs_mount.fs_id | quote }}
    storage.ktsys.cloud/efs_name: {{ $efs_mount.fs_name | quote }}
    storage.ktsys.cloud/efs_ap_id: {{ $efs_ap.id | quote }}
    storage.ktsys.cloud/efs_path: {{ $efs_ap.path | quote }}
    {{- with $efs_mount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  capacity:
    storage: 5Gi  # Any number will do, we are just required to specify a storage capacity
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ $job.storage.efs.storageClass }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ $efs_mount.fs_id }}::{{ $efs_ap.id }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $PVC_NAME }}
  annotations:
    storage.ktsys.cloud/efs_fs_id: {{ $efs_mount.fs_id | quote }}
    storage.ktsys.cloud/efs_name: {{ $efs_mount.fs_name | quote }}
    storage.ktsys.cloud/efs_ap_id: {{ $efs_ap.id | quote }}
    storage.ktsys.cloud/efs_path: {{ $efs_ap.path | quote }}
    {{- with $efs_mount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $job.storage.efs.storageClass }}
  volumeName: {{ $PV_NAME }}
  resources:
    requests:
      storage: 5Gi  # Any number will do, we are just required to specify a storage capacity

{{- end }} {{/* # end range $efs_ap */}}
{{- end }} {{/* # end range $efs_mount */}}
{{- end }} {{/* # end range volumes */}}
